version: '3.7'

services: 
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    ports: 
      - '8080:80'
    depends_on:
      - app
    networks:
      - default-network
  app:
    build: 
      context: ./node
    container_name: app
    networks: 
      - default-network
    volumes: 
      - ./node:/usr/src/app
    tty: true
    ports: 
      - "3000:3000"
    depends_on: 
       - db

  db:
    build: 
      context: ./mysql
    container_name: db
    restart: always
    tty: true
    networks:
      - default-network
    volumes:
      - ./mysql/volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

    

networks: 
  default-network:
    driver: bridge      
